server:
  port: 8080
  tomcat:
      uri-encoding: utf-8
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true
spring:
  # Redis
  redis:
      database: 12
      host: localhost
      port: 6379
      #密码默认为空，注释即可，要添加密码，去掉注释添加就行
#      password:
      pool: #star
        maxActive: 8
        maxWait: -1
        maxIdle: 8
        minIdle: 0 #end
      # 连接超时时间（毫秒）
      timeout:  0
      # 默认的数据过期时间，主要用于shiro权限管理
      expire: 2592000
logging:
    file: ./logs/log.log
    level:
      com.hope: DEBUG
      tk.mybatis: DEBUG
      org.springframework: WARN