#配置服务消费者
server:
  port: 8888
spring:
  application:
    name: eureka-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#开启hystrix 指标
feign:
  hystrix:
    enabled: true
# 端点管理 hystrixDashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"
