#在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为，在application.properties添加以下配置：
server:
  port: 8761  	#官方
spring:
  application:
    name: eureka-server
  cloud:
    inetutils:
      ignored-interfaces:             #忽略docker0网卡以及 veth开头的网卡
        - docker0
        - veth.*
      preferred-networks:             #使用正则表达式,使用指定网络地址
        - 192.168
        - 10.0
eureka:
  instance:
    hostname: localhost 	#配置主机名
  server:
      #关闭自我保护机制，防止失效的服务也被一直访问 （开发环境)
    enable-self-preservation: false
    #该配置可以修改检查失效服务的时间，每隔5s检查失效服务，默认该配置是 60s （开发环境)
    eviction-interval-timer-in-ms: 5000
  client:
#表示是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
#表示是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
#设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/